server:
    #运行端口号
    port: 8099
spring:
    application:
        name: diary
    #数据库连接
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/diary?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
        username: root
        password: 33RushB
        driver-class-name: com.mysql.cj.jdbc.Driver
swagger:
    enabled: true

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath:com/diary/mapper/xml/*.xml

jwt:  #token生成
    timeout: 180000000000    # 过期时间 毫秒
    headname: "diary"  # 请求头


path:
    #文件上传根目录 设置
    upload: static/upFiles